### ISSUE TITLE
www/node build failure

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedbsd-ports#14] opened 2016-07-13 22:36 UTC
www/node fails to build on the hardened/current/master-libressl branch. Build log attached.

[2016-07-13_node-6.3.0.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/362623/2016-07-13_node-6.3.0.log.txt)

**Comment by Sp1l** [comment] 2016-07-20 20:03
The issue is that Node can't/won't build with LibreSSL at all. There's an option to build it with OpenSSL 1.0.2 included in Node's source tarball.

See https://github.com/nodejs/node/issues/428 for more thorough explanation.

OpenBSD is at Node4 (LTS) for which a patch-set is available.
Gentoo's patch also failed after the upgrade to Node 5...

**Comment by lattera** [comment] 2016-07-20 20:04
Is there a way we can enhance the Ports framework to detect whether we're running with LibreSSL-in-base? We could use that, then, in the www/node port to determine whether we should bring in ports OpenSSL as a depenency.

**Comment by lattera** [comment] 2016-08-21 01:57
Any updates on this, @Sp1l?

**Comment by lattera** [comment] 2016-09-08 21:48
Your recent commit to determine which crypt lib is in base (OpenSSL versus LibreSSL), 8deeee4ec9a565d2072c77d8323ca7a6277b8bf2, looks good. Attached is the log of a new build failure.

[node-6.5.0.log.txt](https://github.com/HardenedBSD/hardenedbsd-ports/files/462774/node-6.5.0.log.txt)

**Comment by Sp1l** [comment] 2016-09-09 13:03
Detection of LibreSSL in base fixed with 8deeee4ec9a565d2072c77d8323ca7a6277b8bf2

**Closed** 2016-09-09 14:13 UTC
Labels: bug, LibreSSL
